from config.env import env

REDIS_REALTIME_DB_HOST = env("REDIS_REALTIME_DB_HOST")
REDIS_COINS_HOST = env("REDIS_COINS_HOST")
REDIS_COINS_PORT = env("REDIS_COINS_PORT")
REDIS_CHATS_HOST = env("REDIS_CHATS_HOST")
REDIS_CHATS_PORT = env("REDIS_CHATS_PORT")
REDIS_USER_HOST = env("REDIS_USER_HOST")
REDIS_USER_PORT = env("REDIS_USER_PORT")